
services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      
        autoconfigure: true 

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Form\UserType:
        tags: ['form.type']


        
